import './globals.css';
import { Nanum_Gothic } from 'next/font/google';

const nanumGothic = Nanum_Gothic({
  weight: ['400', '700', '800'],
  subsets: ['latin'],
  variable: '--font-nanum-gothic',
});

export const metadata = {
  title: 'Next Trello',
  description: 'Generated by min33sky',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-[#F5F6F8] antialiased ${nanumGothic.variable} font-nanumGothic `}
      >
        {children}
      </body>
    </html>
  );
}
