import Modal from '@/components/Modal';
import './globals.css';

export const metadata = {
  title: 'Next Trello',
  description: 'Generated by min33sky',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`custom-scrollbar bg-[#F5F6F8] antialiased `}>
        {children}
        <Modal />
      </body>
    </html>
  );
}
